from django.urls import path

from .views import (
    HomePage,
    ShowAbout,
    ThemesOnSectionList,
    ThemeList,
    MessagesOnThemeList,
    CreateMessage,
    CreateTheme,
    CreateThemeWithSection,
)
urlpatterns = [
    path(
        "",
        HomePage.as_view(),
        name="home",
    ),
    path(
        "themes/",
        ThemeList.as_view(),
        name="theme_list",
    ),
    path(
        "about/",
        ShowAbout.as_view(),
        name="about",
    ),
    path(
        "section/<int:section_id>/",
        ThemesOnSectionList.as_view(),
        name="themes_on_section",
    ),
    path(
        "section/<int:section_id>/theme/<int:theme_id>/",
        MessagesOnThemeList.as_view(),
        name="messages_on_theme",
    ),
    path(
        "section/<int:section_id>/theme/<int:theme_id>/create_message/",
        CreateMessage.as_view(),
        name="create_message",
    ),
    path(
        "create_theme/",
        CreateTheme.as_view(),
        name="create_theme",
    ),
    path(
        "section/<int:section_id>/create_theme/",
        CreateThemeWithSection.as_view(),
        name="create_theme_with_section",
    ),
]
