services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: web_forum
    restart: always
    depends_on:
      - postgres
    networks:
      - backend
      - server

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_forum
    restart: always
    ports:
      - '80:80'
    depends_on:
      - web
      - postgres
    networks:
      - server

  postgres:
    image: postgres:18
    container_name: postgres_forum
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_DB: db_forum
      PGDATA: /var/lib/postgresql/18/data/pgdata_forum
    ports:
      - '5432:5432'
    volumes:
      - pgdata_forum:/var/lib/postgresql/18/data/pgdata_forum
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: always
    tty: true
    stdin_open: true
    networks:
      - backend


networks:
  backend:
  server:


volumes:
  pgdata_forum:
