FROM nginx:1.29

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY ./app/static /var/www/VelikForum/static
COPY ./app/media /var/www/VelikForum/media

RUN chmod -R 755 /var/www/VelikForum/static
RUN chmod -R 755 /var/www/VelikForum/media

RUN chown -R www-data:www-data /var/www/VelikForum/static
RUN chown -R www-data:www-data /var/www/VelikForum/media

EXPOSE 80