services:
  web:
    build: .
    container_name: web_forum
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - web_data:/web
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:18
    container_name: postgres_forum
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_DB: db_forum
      PGDATA: /var/lib/postgresql/18/data/pgdata_forum
    ports:
      - '5432:5432'
    volumes:
      - pgdata_forum:/var/lib/postgresql/18/data/pgdata_forum
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: always
    tty: true
    stdin_open: true
    networks:
      - backend


networks:
  backend:


volumes:
  pgdata_forum:
  web_data:
