# Generated by Django 5.2.7 on 2025-10-25 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='all_parents', to='forum.message'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['created_at'], name='forum_secti_created_023bad_idx'),
        ),
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theme', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theme', to='forum.section'),
        ),
        migrations.AddField(
            model_name='message',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='forum.theme'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['created_at'], name='forum_theme_created_a86e48_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='forum_messa_created_cd25f1_idx'),
        ),
    ]
