# Generated by Django 5.2.7 on 2025-10-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_message_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='active',
            new_name='is_active',
        ),
    ]
