# Generated by Django 5.2.7 on 2025-10-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_active_message_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='messages_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
